name: Update Slack CLI

on:
  workflow_dispatch:
  schedule:
    - cron: "17 3 * * 1"

permissions:
  contents: write
  pull-requests: write

jobs:
  update-slack-cli:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - name: Update slack-cli
        run: nix run nixpkgs#nix-update -- --flake --version=stable slackcli
      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: "slackcli: update Slack CLI"
          title: "slackcli: update Slack CLI"
          body: "Automated Slack CLI update."
          branch: update/slack-cli
          delete-branch: true
